"""empty message

Revision ID: 2678347ac2a4
Revises: bf990e3c36aa
Create Date: 2020-03-29 18:00:36.995240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2678347ac2a4'
down_revision = 'bf990e3c36aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=True))
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('nickname', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
