"""empty message

Revision ID: 2b79323151be
Revises: 2678347ac2a4
Create Date: 2020-03-29 20:39:29.459358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b79323151be'
down_revision = '2678347ac2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_delete')
    # ### end Alembic commands ###
