"""empty message

Revision ID: 7fb2ee4daed6
Revises: 3f06016d40db
Create Date: 2020-04-01 22:44:59.884089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb2ee4daed6'
down_revision = '3f06016d40db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('host_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'host_id')
    # ### end Alembic commands ###
