"""empty message

Revision ID: 9001a97376c0
Revises: b3ed7f5efe37
Create Date: 2020-03-29 17:44:56.638233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9001a97376c0'
down_revision = 'b3ed7f5efe37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
