"""empty message

Revision ID: 92b53413a92d
Revises: 527c713724c4
Create Date: 2020-04-02 09:07:28.665125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b53413a92d'
down_revision = '527c713724c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_ibfk_1', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'room', ['message_room'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_ibfk_1', 'message', 'user', ['message_room'], ['id'])
    # ### end Alembic commands ###
