"""empty message

Revision ID: 92c4ea9a487e
Revises: a3c9f6feb0ff
Create Date: 2020-04-01 21:58:10.321859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c4ea9a487e'
down_revision = 'a3c9f6feb0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_timestamp', table_name='message')
    op.drop_table('message')
    op.drop_constraint('room_ibfk_1', 'room', type_='foreignkey')
    op.drop_column('room', 'host_id')
    op.add_column('user', sa.Column('rooms', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'room', ['rooms'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'rooms')
    op.add_column('room', sa.Column('host_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('room_ibfk_1', 'room', 'user', ['host_id'], ['id'])
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='message_ibfk_1'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='message_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_message_timestamp', 'message', ['timestamp'], unique=False)
    # ### end Alembic commands ###
