"""empty message

Revision ID: 9b308d95ee03
Revises: 2b79323151be
Create Date: 2020-03-29 22:03:55.496661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b308d95ee03'
down_revision = '2b79323151be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('message', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'room_id')
    op.drop_table('room')
    # ### end Alembic commands ###
