"""empty message

Revision ID: e7ad230a9416
Revises: ef8c3cd2810d
Create Date: 2020-03-30 09:53:30.151853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7ad230a9416'
down_revision = 'ef8c3cd2810d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ip', sa.String(length=255), nullable=True))
    op.drop_column('user', 'email_hash')
    op.drop_column('user', 'website')
    op.drop_column('user', 'password')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'github')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('bio', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('website', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('email_hash', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'ip')
    # ### end Alembic commands ###
