"""empty message

Revision ID: ef8c3cd2810d
Revises: 9b308d95ee03
Create Date: 2020-03-29 23:16:42.614955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8c3cd2810d'
down_revision = '9b308d95ee03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'name')
    # ### end Alembic commands ###
