HTTP_OK =200
HTTP_CREATE_OK=201



USER_ACTION_LOGIN="login"
USER_ACTION_REGISTER="register"
USER_ACTION_QUICK_LOGIN="quicklogin"
USER_VALIDATE="validate"


ROOM_ACTION_JOIN="join"
ROOM_ACTION_REGISTER="register"

MESSAGE_TYPE_CHAT=1
MESSAGE_TYPE_ONLINE=0
MESSAGE_TYPE_PICTURE=2